# Generated by Django 4.0.5 on 2022-07-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.PositiveIntegerField(max_length=5, null=True),
        ),
    ]
